apiVersion: v1
kind: Pod
metadata:
  name: restart-demo-success
  namespace: pod-deepdive
spec:
  restartPolicy: OnFailure
  containers:
  - name: worker
    image: busybox
    command: ["sh", "-c", "echo 'Success!'; exit 0"]

