apiVersion: v1
kind: Pod
metadata:
  name: sidecar-web-logs
  namespace: pod-deepdive
  labels:
    app: sidecar-web-logs
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}
  containers:
  - name: app
    image: busybox
    command:
    - sh
    - -c
    - >
      echo "Live logs (press F5 to refresh)<br>" > /var/www/index.html;
      while true; do echo "$(date) writing logs<br>" >> /var/www/index.html; sleep 2; done
    volumeMounts:
    - name : shared-logs
      mountPath: /var/www
  - name : log-web
    image: nginx:1.25
    ports:
    - containerPort: 80 
    volumeMounts:
    - name: shared-logs
      mountPath: /usr/share/nginx/html
