apiVersion: v1
kind: Pod
metadata:
  name: sidecar-log
  namespace: pod-deepdive
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}
  containers:
  - name: app
    image: busybox
    command:
    - sh
    - -c
    - while true; do echo "$(date) | app is running" >> /var/log/app.log; sleep 5; done
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
  - name: log-shipper
    image: busybox
    command:
    - sh
    - -c
    - tail -f /logs/app.log
    volumeMounts:
    - name: shared-logs
      mountPath: /logs

