apiVersion: v1
kind: Service
metadata:
  name: sidecar-web-svc
  namespace: pod-deepdive
spec:
  type: NodePort
  selector:
    app: sidecar-web-logs
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
