apiVersion: v1
kind: Pod
metadata:
  name: db-guaranteed
  namespace: day4
spec:
  containers:
  - name: mysql
    image: mysql:8
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
