apiVersion: v1
kind: Pod
metadata:
  name: web-burstable
  namespace: day4 
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    resources:
      requests:
        cpu: "200m"
      limits:
        cpu: "500m"

