apiVersion: v1
kind: Pod
metadata:
  name: pod-with-affinity
  namespace: day3
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disk
            operator: In
            values: ["ssd"]
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: region
            operator: In
            values: ["kr-seoul-a"]
  containers:
  - name: nginx
    image: nginx:1.25

