apiVersion: v1
kind: Pod
metadata:
  name: tolerate-spot
  namespace: day3
spec:
  tolerations:
  - key: "spot"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo 'Running on spot node'; sleep 3600"]

