# 02-pod-and-svc-starter.yaml
apiVersion: v1
kind: Pod
metadata:
  name: log-web
  namespace: day2-ops
  labels:
    app: log-web
spec:
  volumes:
  - name: web-logs
    persistentVolumeClaim:
      claimName: web-logs-pvc
  initContainers:
  - name: init-index
    image: busybox:1.36
    command:
    - sh
    - -c
    - |
      echo '<meta charset="UTF-8"><meta http-equiv="refresh" content="5"><h2>Live Cron Logs</h2><hr>' > __FILL__/index.html   # TODO: 여기에 파일 생성 경로 입력
    volumeMounts:
    - name: web-logs
      mountPath: __FILL__                                            # TODO: Init이 쓰는 경로
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
    volumeMounts:
    - name: web-logs
      mountPath: __FILL__                                            # TODO: Nginx가 서빙하는 경로 (/usr/share/nginx/html)
---
apiVersion: v1
kind: Service
metadata:
  name: log-web-svc
  namespace: day2-ops
spec:
  type: NodePort
  selector:
    app: log-web
  ports:
  - port: 80
    targetPort: 80
    # nodePort는 비워두면 자동 할당. 고정하려면 여기에 값 입력(예: 30085)
    # nodePort: __OPTIONAL__

