apiVersion: v1
kind: Namespace
metadata:
  name: day2-ops
---
apiVersion: v1
kind: Pod
metadata:
  name: log-web
  namespace: day2-ops
  labels:
    app: log-web
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx:1.25
    volumeMounts:
    - name: shared-logs
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: log-web-svc
  namespace: day2-ops
spec:
  type: NodePort
  selector:
    app: log-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-writer
  namespace: day2-ops
spec:
  schedule: "*/1 * * * *"        # 1분마다 실행
  timeZone: "Asia/Seoul"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: shared-logs
            emptyDir: {}
          containers:
          - name: writer
            image: busybox:1.36
            volumeMounts:
            - name: shared-logs
              mountPath: /var/logs
            command:
            - sh
            - -c
            - |
              d=$(date '+%Y-%m-%d %H:%M:%S');
              echo "<p>✅ Cron fired at $d</p>" >> /var/logs/index.html

