apiVersion: batch/v1
kind: Job
metadata:
  name: hello-once
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 2
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: say
        image: busybox:1.36
        command: ["sh","-c","echo 'Job done'; exit 0"]
