apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-writer
  namespace: day2-ops
spec:
  schedule: "*/1 * * * *"       # 1분마다
  timeZone: "Asia/Seoul"
  concurrencyPolicy: Forbid     # 겹치면 새 회차 건너뜀
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: shared-logs
            persistentVolumeClaim:
              claimName: web-logs-pvc
          containers:
          - name: writer
            image: busybox:1.36
            volumeMounts:
            - name: shared-logs
              mountPath: /var/logs
            command:
            - sh
            - -c
            - |
              d=$(date '+%Y-%m-%d %H:%M:%S')
              echo "<p> Cron fired at ${d}</p>" >> /var/logs/index.html

