apiVersion: v1
kind: Pod
metadata:
  name: log-web
  namespace: day2-ops
  labels:
    app: log-web
spec:
  volumes:
  - name: shared-logs
    persistentVolumeClaim:
      claimName: web-logs-pvc
  initContainers:
  - name: init-index
    image: busybox:1.36
    command:
      - sh
      - -c
      - |
        set -e
        [ -f /data/index.html ] || {
          echo '<meta http-equiv="refresh" content="5">' > /data/index.html
          echo '<h2>Live Cron Logs</h2>' >> /data/index.html
          echo '<p>The page automatically refreshes every 5 seconds.</p>' >> /data/index.html
          echo '<hr>' >> /data/index.html
        }
    volumeMounts:
    - name: shared-logs
      mountPath: /data
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /usr/share/nginx/html

