apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-web
  namespace: day2-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-web
  template:
    metadata:
      labels:
        app: log-web
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: web-logs-pvc
      containers:
        - name: nginx
          image: skilleat/ops2-log-img:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/share/nginx/html

