apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-logs-pvc
  namespace: day2-ops
spec:
  accessModes:
    - ReadWriteOnce   # Minikube 단일노드면 RWO로 충분
  resources:
    requests:
      storage: 1Gi

