apiVersion: batch/v1
kind: CronJob
metadata:
  name: report-daily
spec:
  schedule: "0 1 * * *"          # 매일 01:00
  timeZone: "Asia/Seoul"          # 시간대 고정(권장)
  concurrencyPolicy: Forbid        # 이전 회차가 남아 있으면 새 회차 '건너뜀'
  startingDeadlineSeconds: 600     # 10분 이내 놓친 회차는 뒤늦게라도 실행
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: make-report
            image: busybox:1.36
            command: ["sh","-c","date; echo generate daily report; exit 0"]
